// ═══════════════════════════════════════════════════════════════
// NOTHINGBURGER ENGINE — Constants
// ═══════════════════════════════════════════════════════════════

import type { PrismParameters, PrismPreset, LatticeParameters, ColorParameters } from './types'

// Golden ratio for Fibonacci sphere distribution
export const GOLDEN_RATIO = (1 + Math.sqrt(5)) / 2

// Default node count for the sphere
export const DEFAULT_NODE_COUNT = 1000

// Default color parameters (spectrum = physics-based, original behavior)
export const DEFAULT_COLOR: ColorParameters = {
  mode: 'spectrum',
  single: '#00e5ff',
  palette: ['#ff0066', '#ffaa00', '#00e5ff', '#22ff88'],
  gradient: ['#ff00aa', '#7a00ff', '#00e5ff'],
  gradientAxis: 'y',
  saturation: 1,
}

// Curated palette presets (discrete confetti colors)
export const COLOR_PALETTES: { name: string; colors: string[] }[] = [
  { name: 'NEON', colors: ['#ff0066', '#ffaa00', '#00e5ff', '#22ff88'] },
  { name: 'EMBER', colors: ['#ff3300', '#ff7700', '#ffcc00', '#ffee88'] },
  { name: 'OCEAN', colors: ['#003f88', '#0077b6', '#00b4d8', '#90e0ef'] },
  { name: 'CANDY', colors: ['#ff5d8f', '#ff9ec6', '#a06cd5', '#5fffd0'] },
  { name: 'MONO', colors: ['#ffffff', '#bbbbbb', '#777777'] },
  { name: 'GOLD', colors: ['#3a2a00', '#8a6d00', '#d4af37', '#fff1b8'] },
]

// Curated gradient presets (smooth interpolation stops)
export const COLOR_GRADIENTS: { name: string; colors: string[] }[] = [
  { name: 'PLASMA', colors: ['#ff00aa', '#7a00ff', '#00e5ff'] },
  { name: 'SUNSET', colors: ['#ffd200', '#ff7b00', '#ff006e'] },
  { name: 'AURORA', colors: ['#00ff9d', '#00e5ff', '#7a5cff'] },
  { name: 'FIRE', colors: ['#fff200', '#ff6a00', '#d00000'] },
  { name: 'ICE', colors: ['#ffffff', '#90e0ef', '#0077b6'] },
  { name: 'GHOST', colors: ['#ffffff', '#8899ff', '#1a1a3a'] },
]

// Default lattice parameters
export const DEFAULT_LATTICE: LatticeParameters = {
  enabled: false,
  base: 'tri',
  shape: 'sphere',
  shells: 16,
  edgeWidth: 1.5,
  edgeOpacity: 0.7,
  static: false,
  collapse: 0,
  innerGlow: 0.5,
}

// Default engine parameters
export const DEFAULT_PARAMETERS: PrismParameters = {
  tau: 0.12,
  shapeScale: 1.0,
  refIdx: 1.52,
  dispersion: 0.04,
  prismInt: 1.0,
  rx: 0.3,
  ry: 0.5,
  rz: 0.0,
  bc: 400,
  bw: 1.2,
  bo: 0.5,
  pattern: 'dft',
  harmK: 3,
  phaseV: 1.0,
  dr: 3.0,
  gr: 10,
  ba: 0.04,
  shapeTxt: '',
  spotlight: false,
  gpuMode: false,
  gpuWarp: 0.16,
  gpuHue: 0.02,
  gpuSpin: 1.0,
  gpuV0: false,
  lattice: DEFAULT_LATTICE,
  color: DEFAULT_COLOR,
}

// Visual presets
export const PRESETS: PrismPreset[] = [
  {
    name: 'v0-spotlight',
    label: 'V0',
    params: {
      tau: 0.2,
      shapeScale: 1.0,
      refIdx: 1.52,
      dispersion: 0.04,
      prismInt: 0.55,
      rx: 0,
      ry: 0,
      rz: 0,
      bc: 400,
      bw: 1.0,
      bo: 0.4,
      pattern: 'all',
      harmK: 1,
      phaseV: 0.5,
      dr: 2.4,
      gr: 5,
      ba: 0,
      shapeTxt: 'v0',
      spotlight: true,
      gpuMode: false,
      color: { ...DEFAULT_COLOR, mode: 'single', single: '#ffffff' },
    },
  },
  {
    name: 'reality-bender',
    label: 'REALITY BENDER',
    params: {
      spotlight: false,
      gpuMode: true,
      gpuV0: false,
      gpuWarp: 0.16,
      gpuHue: 0.02,
      gpuSpin: 1.0,
      shapeTxt: '',
      prismInt: 0.8,
      harmK: 3,
      phaseV: 1.1,
      dr: 3.0,
      color: { ...DEFAULT_COLOR },
    },
  },
  {
    name: 'v0-prism',
    label: 'V0 PRISM',
    params: {
      spotlight: false,
      gpuMode: true,
      gpuV0: true,
      gpuWarp: 0,
      gpuHue: 0,
      gpuSpin: 0,
      shapeTxt: 'v0',
      prismInt: 1.6,
      dr: 2.8,
      color: { ...DEFAULT_COLOR },
    },
  },
  {
    name: 'genesis',
    label: 'GENESIS',
    params: {
      spotlight: false,
      gpuMode: false,
      shapeTxt: '',
      color: { ...DEFAULT_COLOR },
      tau: 0.15,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.04,
      prismInt: 1.2,
      rx: 0,
      ry: 0.2,
      rz: 0,
      bc: 300,
      bw: 1.5,
      bo: 0.6,
      pattern: 'dft',
      harmK: 3,
      phaseV: 0.5,
      dr: 3.5,
      gr: 12,
      ba: 0.05,
    },
  },
  {
    name: 'storm',
    label: 'STORM',
    params: {
      spotlight: false,
      gpuMode: false,
      color: { ...DEFAULT_COLOR },
      tau: 0.04,
      shapeScale: 1,
      refIdx: 1.8,
      dispersion: 0.08,
      prismInt: 1.5,
      rx: 1.5,
      ry: 2.0,
      rz: 1.0,
      bc: 800,
      bw: 1.0,
      bo: 0.7,
      pattern: 'gabor',
      harmK: 8,
      phaseV: 5.0,
      dr: 2.0,
      gr: 5,
      ba: 0.01,
    },
  },
  {
    name: 'prayer',
    label: 'PRAYER',
    params: {
      spotlight: false,
      gpuMode: false,
      color: { ...DEFAULT_COLOR },
      tau: 0.25,
      shapeScale: 1,
      refIdx: 1.45,
      dispersion: 0.02,
      prismInt: 0.8,
      rx: 0,
      ry: 0.1,
      rz: 0,
      bc: 150,
      bw: 0.8,
      bo: 0.4,
      pattern: 'sinc',
      harmK: 2,
      phaseV: 0.3,
      dr: 4.0,
      gr: 15,
      ba: 0.06,
    },
  },
  {
    name: 'nova',
    label: 'NOVA',
    params: {
      spotlight: false,
      gpuMode: false,
      color: { ...DEFAULT_COLOR },
      tau: 0.08,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.06,
      prismInt: 2.0,
      rx: 0.5,
      ry: 0.5,
      rz: 0.5,
      bc: 1000,
      bw: 2.0,
      bo: 0.9,
      pattern: 'all',
      harmK: 1,
      phaseV: 1.0,
      dr: 3.0,
      gr: 10,
      ba: 0.08,
    },
  },
  {
    name: 'dna',
    label: 'DNA',
    params: {
      spotlight: false,
      gpuMode: false,
      color: { ...DEFAULT_COLOR },
      tau: 0.1,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.04,
      prismInt: 1.0,
      rx: 0,
      ry: 0.6,
      rz: 0,
      bc: 350,
      bw: 1.2,
      bo: 0.55,
      pattern: 'helix',
      harmK: 4,
      phaseV: 1.5,
      dr: 3.0,
      gr: 8,
      ba: 0.03,
    },
  },
  {
    name: 'void',
    label: 'VOID',
    params: {
      spotlight: false,
      gpuMode: false,
      color: { ...DEFAULT_COLOR },
      tau: 0.3,
      shapeScale: 1,
      refIdx: 2.0,
      dispersion: 0.1,
      prismInt: 0.5,
      rx: 0.05,
      ry: 0.05,
      rz: 0.05,
      bc: 50,
      bw: 0.5,
      bo: 0.3,
      pattern: 'sinc',
      harmK: 1,
      phaseV: 0.1,
      dr: 2.0,
      gr: 20,
      ba: 0.1,
    },
  },
]
