// ═══════════════════════════════════════════════════════════════
// NOTHINGBURGER ENGINE — Constants
// ═══════════════════════════════════════════════════════════════

import type { PrismParameters, PrismPreset, LatticeParameters } from './types'

// Golden ratio for Fibonacci sphere distribution
export const GOLDEN_RATIO = (1 + Math.sqrt(5)) / 2

// Default node count for the sphere
export const DEFAULT_NODE_COUNT = 1000

// Default lattice parameters
export const DEFAULT_LATTICE: LatticeParameters = {
  enabled: false,
  base: 'tri',
  shape: 'sphere',
  shells: 16,
  edgeWidth: 1.5,
  edgeOpacity: 0.7,
  static: false,
  collapse: 0,
  innerGlow: 0.5,
}

// Default engine parameters
export const DEFAULT_PARAMETERS: PrismParameters = {
  tau: 0.12,
  shapeScale: 1.0,
  refIdx: 1.52,
  dispersion: 0.04,
  prismInt: 1.0,
  rx: 0.3,
  ry: 0.5,
  rz: 0.0,
  bc: 400,
  bw: 1.2,
  bo: 0.5,
  pattern: 'dft',
  harmK: 3,
  phaseV: 1.0,
  dr: 3.0,
  gr: 10,
  ba: 0.04,
  shapeTxt: '',
  lattice: DEFAULT_LATTICE,
}

// Visual presets
export const PRESETS: PrismPreset[] = [
  {
    name: 'genesis',
    label: 'GENESIS',
    params: {
      tau: 0.15,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.04,
      prismInt: 1.2,
      rx: 0,
      ry: 0.2,
      rz: 0,
      bc: 300,
      bw: 1.5,
      bo: 0.6,
      pattern: 'dft',
      harmK: 3,
      phaseV: 0.5,
      dr: 3.5,
      gr: 12,
      ba: 0.05,
    },
  },
  {
    name: 'storm',
    label: 'STORM',
    params: {
      tau: 0.04,
      shapeScale: 1,
      refIdx: 1.8,
      dispersion: 0.08,
      prismInt: 1.5,
      rx: 1.5,
      ry: 2.0,
      rz: 1.0,
      bc: 800,
      bw: 1.0,
      bo: 0.7,
      pattern: 'gabor',
      harmK: 8,
      phaseV: 5.0,
      dr: 2.0,
      gr: 5,
      ba: 0.01,
    },
  },
  {
    name: 'prayer',
    label: 'PRAYER',
    params: {
      tau: 0.25,
      shapeScale: 1,
      refIdx: 1.45,
      dispersion: 0.02,
      prismInt: 0.8,
      rx: 0,
      ry: 0.1,
      rz: 0,
      bc: 150,
      bw: 0.8,
      bo: 0.4,
      pattern: 'sinc',
      harmK: 2,
      phaseV: 0.3,
      dr: 4.0,
      gr: 15,
      ba: 0.06,
    },
  },
  {
    name: 'nova',
    label: 'NOVA',
    params: {
      tau: 0.08,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.06,
      prismInt: 2.0,
      rx: 0.5,
      ry: 0.5,
      rz: 0.5,
      bc: 1000,
      bw: 2.0,
      bo: 0.9,
      pattern: 'all',
      harmK: 1,
      phaseV: 1.0,
      dr: 3.0,
      gr: 10,
      ba: 0.08,
    },
  },
  {
    name: 'dna',
    label: 'DNA',
    params: {
      tau: 0.1,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.04,
      prismInt: 1.0,
      rx: 0,
      ry: 0.6,
      rz: 0,
      bc: 350,
      bw: 1.2,
      bo: 0.55,
      pattern: 'helix',
      harmK: 4,
      phaseV: 1.5,
      dr: 3.0,
      gr: 8,
      ba: 0.03,
    },
  },
  {
    name: 'void',
    label: 'VOID',
    params: {
      tau: 0.3,
      shapeScale: 1,
      refIdx: 2.0,
      dispersion: 0.1,
      prismInt: 0.5,
      rx: 0.05,
      ry: 0.05,
      rz: 0.05,
      bc: 50,
      bw: 0.5,
      bo: 0.3,
      pattern: 'sinc',
      harmK: 1,
      phaseV: 0.1,
      dr: 2.0,
      gr: 20,
      ba: 0.1,
    },
  },
  {
    name: 'v0-lattice',
    label: 'v0',
    params: {
      tau: 0.15,
      shapeScale: 1,
      refIdx: 1.52,
      dispersion: 0.03,
      prismInt: 0.3,
      rx: 0,
      ry: 0.15,
      rz: 0,
      bc: 600,
      bw: 1.0,
      bo: 0.4,
      pattern: 'all',
      harmK: 1,
      phaseV: 0.5,
      dr: 2.5,
      gr: 8,
      ba: 0.02,
      lattice: {
        enabled: true,
        base: 'tri',
        shape: 'v0',
        shells: 24,
        edgeWidth: 2.0,
        edgeOpacity: 0.85,
        static: false,
        collapse: 0,
        innerGlow: 0.8,
      },
    },
  },
]
